### ISSUE TITLE
Log spam when Theme-Mineweb

### ISSUE THREAD

**Issue by PHPierrre** [MineWeb/MineWebCMS#10]
Config :

![image](https://user-images.githubusercontent.com/8572485/39143752-1d0aeb0a-472f-11e8-9253-8150de217e62.png)

`2018-04-23 19:44:54 Error: Theme (Mineweb) check supported: Invalid version : ` in error.log

Other theme 

`2018-04-23 19:48:09 Error: Theme (Universal) check supported: Invalid version : ` in error.log

**Comment by Eywek** [comment]
Fixed ed4d5eb9b07ff024e044362657c8488eb32a188c
