### ISSUE TITLE
Erreur à la création de la DB 

### ISSUE THREAD

**Issue by Rouchesta** [MineWeb/MineWebCMS#112]
Bonjour à tous,

Je viens d'installer la version 1.7
J'ai un soucis une fois que j'ai valider l'étape de connexion à la base de données.

`[PDOException] SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'getKey' at line 1
#0 /var/www/humanitycraft/lib/Cake/Model/Datasource/DboSource.php(458): PDOStatement->execute(Array)
#1 /var/www/humanitycraft/lib/Cake/Model/Datasource/DboSource.php(424): DboSource->_execute('getKey', Array)
#2 /var/www/humanitycraft/lib/Cake/Model/Datasource/DboSource.php(666): DboSource->execute('getKey', Array, Array)
#3 /var/www/humanitycraft/lib/Cake/Model/Datasource/DboSource.php(609): DboSource->fetchAll('getKey', Array, Array)
#4 /var/www/humanitycraft/lib/Cake/Model/Model.php(809): DboSource->query('getKey', Array, Object(AppModel))
#5 /var/www/humanitycraft/app/Controller/AppController.php(105): Model->__call('getKey', Array)
#6 /var/www/humanitycraft/app/Controller/AppController.php(105): AppModel->getKey('name')
#7 /var/www/humanitycraft/lib/Cake/Error/ExceptionRenderer.php(97): AppController->__initConfiguration()
#8 /var/www/humanitycraft/lib/Cake/Error/ErrorHandler.php(118): ExceptionRenderer->__construct(Object(PDOException))
#9 [internal function]: ErrorHandler::handleException(Object(PDOException))
#10 {main}

Try to remove files on directory /app/tmp/cache/`

J'ai déjà essayer de vider le cache comme indiqué mais rien n'y fait.
Des idées ?

Merci.
Bonne soirée.

**Comment by KuroSenseii** [comment]
installe la 1.6.2 pas la 1.7

**Comment by Rouchesta** [comment]
Je vais tester. Merci.

**Comment by Kuosai** [comment]
J'ai la même erreur
