### ISSUE TITLE
 XSS(Stored) in MineWebCMS_v1.7.0

### ISSUE THREAD

**Issue by Ryan0lb** [MineWeb/MineWebCMS#123]
Affected software:MineWebCMS_v1.7.0
Type of vulnerability: XSS (Stored)
Discovered by: Ryan0lb

details:
Open this url “http://127.0.0.1/admin/“ and login in
![image](https://user-images.githubusercontent.com/15329046/54516044-c4601a80-4998-11e9-85cd-56d7bfbb6abf.png)
and Click the "Customization" and view the News
we can add a new article
![image](https://user-images.githubusercontent.com/15329046/54517010-844e6700-499b-11e9-8a61-d0cbcf85a0dc.png)
We can control this parameter via "title",and we can insert the payload:"<script>alert("test")</script>" in title
![image](https://user-images.githubusercontent.com/15329046/54517158-df805980-499b-11e9-8082-272df3f77c6f.png)
finally,submit!
The malicious javascript payload executed for it successlly
![image](https://user-images.githubusercontent.com/15329046/54517227-09398080-499c-11e9-900a-a8afbf714305.png)
and open the article's url:"http://127.0.0.1/blog/1-php",The malicious javascript payload executed for it successlly too
![image](https://user-images.githubusercontent.com/15329046/54517337-5c133800-499c-11e9-99ec-19560cd2816d.png)
Without any filtering on publish the article, we can easily trigger malicious XSS Payload and attack every visitor maliciously.

**Comment by Eywek** [comment]
Hello,
Thank’s for the report. But this is a deliberate behavior. Users should be able to use html tags on news (and pages...). Also, I don’t think this is a critical vulnerability. Indeed, the administrator can already access users account via the admin dashboard or he can upload whatever he want on his website.

**Comment by Ryan0lb** [comment]
Hi,friend
as a Penetration tester,Maybe we can get the account of admin by some ways,For example,we can use the weak password to get administrative privileges for someone use our's cms,
Then execute malicious code by XSS, to execute phishing attacks, and to obtain private information from other viewers.
thanks for your reply!
Many thanks!

**Comment by Eywek** [comment]
And what informations can you get that you don't already have via the admin account?

**Comment by Ryan0lb** [comment]
Hi,
attackers can Implante malicious mining script,Digging on the viewer's machine, during he did not close the browser。
Many thanks!

**Comment by Cristian-Bejan** [comment]
Are these security vulnerabilities fixed?
