### ISSUE TITLE
unable to connect to the website

### ISSUE THREAD

**Issue by Scuisond** [MineWeb/MineWebCMS#124]
Hi, for the last 3 days no one can connect to the website and no one find a fix on discord. When anyone try to connect this message appear 

> Erreur : Erreur interne, veuillez réésayer

 and obviously i can't go to the admin panel to try to solve it. I have no clue help me please.

**Comment by KuroSenseii** [comment]
look on the discord, the answer is in the message pin since 03/03/2019...

**Comment by Scuisond** [comment]
Hi, it's me again, i tried it, but nothing change. I tried the changes, but the most part was the same as before. I also tried to delete the tmp folder content, but nothing change. Maybe i have done the wrong thing, but i don't know what is the problem.

**Comment by Eywek** [comment]
Give us `app/tmp/logs/error.log` file content please

**Comment by Scuisond** [comment]
[error.log](https://github.com/MineWeb/MineWebCMS/files/2992915/error.log)

**Comment by Eywek** [comment]
Try to remove the plugin TwoFactorAuth from `app/Plugins`

**Comment by Scuisond** [comment]
I tried it but the only file who seams like TwoFactorAuth was Auth and it change absolutly nothing

**Comment by adrienluitot** [comment]
@Scuisond Come on this discord : https://discordapp.com/invite/3QYdt8r It's a French support but we can speak English if you are.
