### ISSUE TITLE
Problème lors de la création du compte

### ISSUE THREAD

**Issue by AzhukOffi** [MineWeb/MineWebCMS#129]
Bonjour,
J'ai un problème avec le CMS lors de la création du compte admin (pendant l'installation)
Je n'ai aucune log d'erreur apache mais j'ai ceci dans les logs mineweb : https://pastebin.com/dz2m0a7T

Comment réglez ce problème ?

**Comment by KuroSenseii** [comment]
reponse sur le discord en message epingler

**Comment by AzhukOffi** [comment]
dans visits le varchar ip est déjà à 40

**Comment by DarkScientist** [comment]
Problème réglé ?

**Comment by AzhukOffi** [comment]
Non, mais je doit avoué avoir un peu abandonné après 2 relances discord :/

**Comment by AzhukOffi** [comment]
Bon, au final par je ne sais quelle miracle, ça remarche
