### ISSUE TITLE
Url d'un bouton incorrect

### ISSUE THREAD

**Issue by FredericFernandes** [MineWeb/MineWebCMS#130]
Bonjour à vous,

![screen](https://user-images.githubusercontent.com/11654499/56459928-3f06c600-639b-11e9-825e-56ab5e5d59f4.png)

Le bouton 1) du screen nous redirige vers "/admin/user" alors que nous somme dans le panel du "slider". 
La bonne redirection doit être : "/admin/slider".
Voilà.
Merci d'avance.

**Comment by DarkScientist** [comment]
Le bouton annuler redirige normalement vers l'accueil qui est /admin/user non? Ce qui là est ce qui est fait ?

**Comment by FredericFernandes** [comment]
Nop "/admin/user" c'est la liste des utilisateurs.

**Comment by DarkScientist** [comment]
Tentative de correction du bug avec ma PR : https://github.com/MineWeb/MineWebCMS/pull/131

**Comment by DarkScientist** [comment]
Issue réglée par la PR https://github.com/MineWeb/MineWebCMS/pull/132 , effectif à la prochaine release, closed !!
