### ISSUE TITLE
Probleme de static a l'installation des themes

### ISSUE THREAD

**Issue by lbopp42** [MineWeb/MineWebCMS#147]
Bonjour,
Des que j'installe un theme qui est different de celui par default, il me manque des statics. Le theme essaye d'aller dans <racine_du_site>/app/webroot/theme/.... sauf que cela n'existe pas. L'installation est fait via le panel et les permissions sont en 775 user:www-data. Est ce que le probleme vient de la derniere mise a jour ou un probleme d'intallation de ma part dans ce cas j'aurais besoin de savoir ou.
Cordialement,
Downer

**Comment by MaximeMichaud** [comment]
Je crois que cela serait de ton côté. Tu peux toujours passé sur le discord.
https://discordapp.com/invite/VYuvCZE
