### ISSUE TITLE
Gaminerie dans le code d'une des pages

### ISSUE THREAD

**Issue by WeeskyBDW** [MineWeb/MineWebCMS#151]
dans le code de la page /user/ajax_login, entre la ligne 150 et 180, il y a une variable eyweklapute défini à 1 mais qui n'est apparemment pas utilisé

Je n'es pas trouvé le fichier en question dans les views et rien dans le routes.php. Pas motivé à faire une grosse recherche dans le code.

Si cette page a été update, merci de clos cette issue (j'ai vu ça sur 2 sites utilisant Mineweb mais peut-être ne sont t'ils plus à jour

c'est rien comme truc mais bon ça coute rien d'y retirer non plus

**Comment by WeeskyBDW** [comment]
j'ai trouvé le lien '/user/ajax_login' dans le code de la page principale, à la ligne 287

**Comment by Eywek** [comment]
C’est sur un thème en particulier, mais je me rappel plus du nom

**Comment by KuroSenseii** [comment]
c'est dans le theme award https://github.com/ClementGuerin/Theme-Awards/blob/master/Layouts/default.ctp

**Comment by WeeskyBDW** [comment]
Ok donc je clos cette issue
