### ISSUE TITLE
There is a Stored XSS in MineWebCMS 1.70.

### ISSUE THREAD

**Issue by Lilc1** [MineWeb/MineWebCMS#154]
Adding code options in the Preferences other page via /MineWebCMS/admin/configuration results in Stored XSS.

![image](https://user-images.githubusercontent.com/55877767/66814923-fc98fd00-ef69-11e9-9a40-6a3e8e1841f9.png)
![image](https://user-images.githubusercontent.com/55877767/66814935-002c8400-ef6a-11e9-87a9-c8f56c7b4698.png)
![image](https://user-images.githubusercontent.com/55877767/66816826-4fc07f00-ef6d-11e9-8225-30d09d71938c.png)
![image](https://user-images.githubusercontent.com/55877767/66816873-636be580-ef6d-11e9-8c11-5afb2b9dc563.png)

The image only shows the acquisition of cookies, this vulnerability can also be used for intranet detection, keyloggers and other operations.

**Comment by Eywek** [comment]
duplicate https://github.com/MineWeb/MineWebCMS/issues/123
