### ISSUE TITLE
API qui ne fonctionne pas !

### ISSUE THREAD

**Issue by SkinDePewDiePie** [MineWeb/MineWebCMS#170]
Bonjour,
Je viens suite à mon problème d'API, en fait lorsque je veux par exemple recupérer ma tête, ca me retourne une image de Steve, alors que si je vais sur un autre site utilisant MineWeb ca marche.

Voici un codepen: https://codepen.io/SkinDePewDiePie_/pen/OJJzJOq

Mon site utilise https:// et la redirection vers www.
Mon espace disque est à 98% (2 sites installés sur le vps)

Vous pensez que ca pourrait venir de là?

Cordialement
-Matteo.

**Comment by DarkScientist** [comment]
Tu as désactivé L'API ? Tu veux utiliser les têtes et skins mojang ou persos ?

**Comment by SkinDePewDiePie** [comment]
Non. Mojang ok, car upload skin c'est CHIANT

**Comment by SkinDePewDiePie** [comment]
JE CLOSE !
Pour ceux qu'ils veulent la réponse:
Bah si tu actives l'api et que tu upload rien bah ça te retournera Steve (reponse de DarkScientist)
