### ISSUE TITLE
2fa?

### ISSUE THREAD

**Issue by GeekCornerGH** [MineWeb/MineWebCMS#171]
Bonjour à tous ! J'aime bien MineWeb mais j'aimerais qu'on m'explique un truc: c'est noté dans le changelog que le 2fa est disponible dans la version 1.7.0+ mais j'ai beau avoir 1.7.0 (que j'ai mis à jour en 1.8.2 hier) je ne vois nul part le 2fa dans mon profil. j'ai souvenir d'une version d'un site ou j'avais activé le 2fa mais il a planté et j'ai réinstallé et plus de 2fa. Je sais cette question est bête mais c'est une fonction que j'appréciais beaucoup. Merci d'avance pour votre réponse et bonne continuation avec ce cms.
GeekCorner

PS: je ne peux plus passer Discord

**Comment by MaximeMichaud** [comment]
Bonjour,
D'après ce que j'ai plus, comprendre, c'est que ce sont les thèmes qui ne sont plus mis à jour, donc les nouvelles fonctions comme par exemple le 2FA ne seront pas présente malheureusement.
J'avais prévu de les updates un par un, mais peut-être que cela n'en vaut plus la peine.

**Comment by geekcorner1** [comment]
Si, ce serait un soulagement que j'ait de nouveau cette fonction @MaximeMichaud, donc même si certains ne l'utilisent pas, moi ce serait le cas... Alors ben comme tu veux mais tu serais mon "sauveur" si tu fais ça (rien que pour le thème Maven, cest celui que j'utilise).
Bref, si tu veux le faire, c'est volontiers, mais sinon ne te force pas, je t'en voudrais pas...

**Comment by MaximeMichaud** [comment]
Alors, je regarderai ça ^^
Je ne suis plus du staff depuis hier, donc il se peut que je ne puisse pas trop demander d'aide concernant l'ajout de cette fonctionnalité. Bref, je regarderai & je ferais de mon mieux pour l'ajouter malgré que je n'ai presque jamais faite de PHP durant ces dernières années.

**Comment by geekcorner1** [comment]
Ok merci beaucoup

**Comment by MaximeMichaud** [comment]
Malheureusement, je ne pourrais pas.
J'avais pour but de mettre à jour & d'intégrer pour chaque thème, mais l'administrateur sur le discord n'a pas voulu me donner accès aux archives sous le prétexte que je n'étais pas "agréable".
Pour revenir à l'issue, tu peux l'activer toi-même avec cette documentation : https://docs.google.com/document/d/1oxKow2vn84yX4O9aMbwsI5QjBiiy5NcXyDuecmtbbH8/edit

**Comment by GeekCornerGH** [comment]
J'y comprends rien. Je n'ai plus qu'à attendre. Merci quand même !

Le dim. 24 nov. 2019 à 21:42, Maxime Michaud <notifications@github.com> a
écrit :

**Comment by GeekCornerGH** [comment]
Je n'y comprends rien. Merci quand même. Je n'ai plus qu'à attendre... Mais c'est pas sur GitHub les thèmes?

**Comment by MaximeMichaud** [comment]
Si, normalement ils y sont tous. Pour modifier dans ton cms, c'est : /var/www/html/app/View/Themed
Je ne crois pas que quelqu'un les updates.. Sinon, cela aurait été fait depuis longtemps.

**Comment by GeekCornerGH** [comment]
C'est trop complexe pour moi...

**Comment by MaximeMichaud** [comment]
Tu peux toujours demander de l'aide sur le Discord de MineWeb.

**Comment by GeekCornerGH** [comment]
Je te rappelle que je ne peux pas discord, trop dur à expliquer

**Comment by MaximeMichaud** [comment]
Commença trop dure? Il y a des gens sur Discord qui t'expliqueront la marche à suivre.
C'est à toi de voir, si tu es prêt à prendre le temps afin de comprendre.

**Comment by GeekCornerGH** [comment]
Je suis finalement passé au thème subtil

**Comment by MaximeMichaud** [comment]
Je vais m'occuper de les update.

**Comment by GeekCornerGH** [comment]
Nice merci!

**Comment by GeekCornerGH** [comment]
Hey, est-ce qu'il y a du neuf?

**Comment by MaximeMichaud** [comment]
> Hey, est-ce qu'il y a du neuf?

Non, malheureusement pas pour 2FA.
Si t'utilises toujours Subtil, je regarderai, mais je manque un peu de temps en ce moment.

**Comment by GeekCornerGH** [comment]
Non je suis repassé à Maven mais subtil a déjà le 2fa... Sinon j'ai vu que
tu as fait des pull requests sur tout les thèmes. C'est pas pour le 2fa?

>

**Comment by MaximeMichaud** [comment]
> Non je suis repassé à Maven mais subtil a déjà le 2fa... Sinon j'ai vu que tu as fait des pull requests sur tout les thèmes. C'est pas pour le 2fa?
> […](#)

Non, je n'ai que commit une modification sur tous les thèmes.
Les autres sont encore dans mon ordinateur.

**Comment by GeekCornerGH** [comment]
Ok alors prends ton temps

**Comment by Eywek** [comment]
Vu que c'est par rapport à thème en particulier, vaut mieux ouvrir une issue dessus si le problème persiste. Je close ici.
