### ISSUE TITLE
Problème liaison serveur-site | RCON

### ISSUE THREAD

**Issue by DargelosDev** [MineWeb/MineWebCMS#18]
Bonjour / Bonsoir,

J'essaie de lié mon site & mon serveur via RCON, mais une seul et même erreur reviens sans arrêt. 
(Tout est bien activé dans le server.properties, et tout est bien remplie partout).
Voici l'erreur du panel en screen : http://image.noelshack.com/fichiers/2018/17/3/1524667700-erreur.png
Erreur du RCON dans error.log : https://hastebin.com/tedivodaqu.cpp

Merci à vous pour vos futur réponses. 
@Eywek

**Comment by Eywek** [comment]
D'après l'erreur de php, le problème vient plutôt de ta configuration minecraft ou de l'un de tes hébergeurs. 
```
unable to connect to 149.202.65.79:28899 (Connexion terminée par expiration du délai d'attente)
```

**Comment by DargelosDev** [comment]
Je ne comprend pas, toute la configuration est bonne. Et l’hébergeur ça m'étonnerai, ça marchait bien avant. Ces problèmes sont survenue du moment que j'ai fais les mises à jour ^^.
