### ISSUE TITLE
[BUG] Erreur lors d'un achat en boutique (commande à executer)

### ISSUE THREAD

**Issue by Ariouz** [MineWeb/MineWebCMS#181]
Lorsque on veut effectuer une commande à l'achat d'un produit sur la boutique, une erreur apparait en console et la commande ne s'effectue pas.

Voici l'erreur: https://pastebin.com/RFPUCmhb

**Comment by MaximeMichaud** [comment]
Le plugin est rouge dans /plugins ?
Si oui, c'est très probablement un problème avec ProtocolLib
Voilà la version fix : 
https://github.com/MineWeb/ServerBridge/raw/no-injector/mineweb_bridge-2.0.0.jar

**Comment by nivcoo** [comment]
Update : Tu peux trouver la bonne version sur la documentation (3.0.2)
