### ISSUE TITLE
[Fonctionnalité] Login via LDAP

### ISSUE THREAD

**Issue by Celemo** [MineWeb/MineWebCMS#188]
Serait-il possible d'implémenter la connection via un serveur LDAP ? C'est une fonctionnalité qui me serait très utile sur le site de mon serveur.

**Comment by Celemo** [comment]
Désolé, j'ai mis le tag bug sans nécessité 😅

**Comment by MaximeMichaud** [comment]
Salut ! Je vais regardé ce qu'est LDAP, mais tu peux m'expliquer ?
