### ISSUE TITLE
chore: bump version to 1.8.4 (development)

### ISSUE THREAD

**Issue by MaximeMichaud** [MineWeb/MineWebCMS#191]
J'aurais besoin de :
https://github.com/MineWeb/MineWebCMS/commit/0adcb4197c7a4eb5970e2c77eac51be4048c0c82
Sur : 
https://github.com/MineWeb/MineWebCMS/blob/development/VERSION

Cela a été oublié.

**Comment by Eywek** [comment]
Pourquoi?

**Comment by MaximeMichaud** [comment]
Mon script d'installation Linux a la possibilité d'installer celle de dev.
Normalement, tu mettais la version avec la dernière release.
Alors, pourquoi pas ?

**Comment by Eywek** [comment]
Parce que mon script de deploy le gère pas comme ça. Je vais check mais ça devrait pas être bloquant pour ton install la version, ça te dira jusque t’es pas à jour

**Comment by MaximeMichaud** [comment]
Justement, c'est ça ma problématique.
Le reste est niquel. C'est juste embêtant avoir 1.7 sur la version 1.8.4

**Comment by MaximeMichaud** [comment]
Up
