### ISSUE TITLE
[BUG] BOUTIQUE

### ISSUE THREAD

**Issue by UntekFR** [MineWeb/MineWebCMS#196]
Bonjour

J'ai rencontré un récent problème avec la boutique 
Quand j'achète un grade sur la boutique 
Il est écrit en rouge Vous devez être connecté pour acheter l'article KIT PILLAGE !
Alors que je suis connecté sur le site et en jeux 
Voici un screen de l'erreur :
http://prntscr.com/qw5zbx

Avez vous une solution à ce problème s'il vous plait ?

**Comment by nivcoo** [comment]
Utilise le plugin pour lier, ensuite le bug a été corrigé il sera la dans la prochaine MAJ

**Comment by UntekFR** [comment]
Oui j'ai le plugin déjà sa marchait avant je vais attendre la prochaine maj

**Comment by nivcoo** [comment]
Cette maj corrige le probleme
