### ISSUE TITLE
Problème boutique

### ISSUE THREAD

**Issue by MrAnthonyPvP** [MineWeb/MineWebCMS#20]
Bonsoir,
J'ai la page de dédipass qui ne s'affiche plus comment je peut résoudre se problèmes ? merci. 
http://image.noelshack.com/fichiers/2018/17/4/1524765675-shop.png
http://image.noelshack.com/fichiers/2018/17/4/1524765675-shop2.png

@Eywek

**Comment by Eywek** [comment]
Je ne peux pas voir tes screens
