### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by DJantonin71** [MineWeb/MineWebCMS#205]
Bonjour,

J'ai un petit problèe quand on s'inscrit sur mon site, il y a une erreur qui dit ": Erreur interne, veuillez réessayer" mais quand on se connecte le compte est bien créer.

Lien du site: http://deitocommunity.fr/

Connaissez vous comment réglé le bug.

**Comment by nivcoo** [comment]
Bonjour, nous avons un discord sinon il nous faut l’error.log comme marqué sur la doc même si c’est probablement le mail de confirmation qui ne s’envoie pas et à se moment là il faut corriger les paramètres smtp (ou en mettre si c’est pas le cas) ou désactivé cette option dans les parametres généraux

**Comment by DJantonin71** [comment]
ok

**Comment by locness3** [comment]
Hello @DJantonin71, ton problème est-il résolu? Si oui, je t'invite à fermer cette Issue.
