### ISSUE TITLE
Connexion serveur/site liée ?

### ISSUE THREAD

**Issue by AzonFR** [MineWeb/MineWebCMS#207]
Bonjour, existe t-il un plugin qui permet que la connexion au serveur soit lié avec le site ? J'ai vu le plugin Auth mais qui est spécialement fait pour une connexion via launcher mais serait-il possible de le convertir en plugin spigot ? J'ai regardé je n'arriverai pas à le modifier de moi-même...
Les mots de passe sont cryptés en AES-128 il me semble et nécessite donc une clé sinon j'aurai mis dans un plugin comme AuthMe par exemple la database de MineWeb et ça aurait été simple mais du coup non..
Si quelqu'un peut m'aider ça serait super et je pense que pas mal de personnes aimerait que ce plugin existe :)
Merci

**Comment by AzonFR** [comment]
J'ai vu aussi ce plugin https://www.spigotmc.org/resources/authplugin.70093/ mais qui ne fonctionne pas avec PaperSpigot 1.8.8 malheureusement... Je vais essayer de contacter le développeur.

**Comment by nivcoo** [comment]
Ils sont pas en AES, c'est une méthode de chiffrage pas de cryptage, c'est du BCRYPT par default mais il y a la migration automatique des mots de passe, donc tu peux mettre SHA-512 et quand les personnes vont se connecter au site le mot de passe va se changer automatique en SHA-512 mais avec authme il y a quelques changement a faire au niveau des fichiers du CMS

**Comment by AzonFR** [comment]
Ah d'accord merci et comment on pourrait faire du coup ?

**Comment by AzonFR** [comment]
Du coup je viens de regarder et les mots de passe sont cryptés et stockés en SHA-256 donc je vais pouvoir faire mon plugin :) Merci pour ton aide
