### ISSUE TITLE
[BUG] Erreur : Une erreur interne est survenue (200).

### ISSUE THREAD

**Issue by Chaxiraxi** [MineWeb/MineWebCMS#210]
**Description du bug**

Bonjour, je suis en train d'installer le CMS sur mon site web en local sur mon PC. J'ai complètement réinstallé XAMPP, et j'ai cloné le git dans *htdocs* Sauf que quand il me demande de me connecter à la base de données, il me retourne l'erreur *Erreur : Une erreur interne est survenue (200).*, et je ne vois pas d'où vient le problème, puis que par définition, l'erreur 200 est une réussite, et pas une erreur.

**Pour reproduire le bug**

Étapes pour reproduire le bug :

1. Aller à la page d'installation *'/opt/lampp/htdocs/MineWebCMS/'*

2. Rentrer ses identifiants et sa config

3. Cliquer sur *'Tester et enregistrer'*

**Ce qui aurait dû se passer**

Normalement, je devrais pouvoir m'authentifier, et commencer l'installation de MineWeb, mais je suis bloqué à la première page.

**Screenshots**

<a href="https://www.noelshack.com/2020-18-1-1587999420-capture-d-ecran-de-2020-04-27-16-42-58.png"><img src="https://image.noelshack.com/minis/2020/18/1/1587999420-capture-d-ecran-de-2020-04-27-16-42-58.png" border="0" alt="1587999420-capture-d-ecran-de-2020-04-27-16-42-58.png - envoi d'image avec NoelShack" title="1587999420-capture-d-ecran-de-2020-04-27-16-42-58.png"/></a>
<a href="https://www.noelshack.com/2020-18-1-1587999420-capture-d-ecran-de-2020-04-27-16-42-26.png"><img src="https://image.noelshack.com/minis/2020/18/1/1587999420-capture-d-ecran-de-2020-04-27-16-42-26.png" border="0" alt="1587999420-capture-d-ecran-de-2020-04-27-16-42-26.png - envoi d'image avec NoelShack" title="1587999420-capture-d-ecran-de-2020-04-27-16-42-26.png"/></a>

**MineWeb:**

 - OS: Kali-Linux (Debian)

 - Navigateur pour accéder à MineWeb : Google-Chrome

 - Version : La dernière

 - Web server : XAMPP

**Comment by nivcoo** [comment]
Salut, tu peux envoyer app/tmp/error.log et si tu as database.log ?

**Comment by nivcoo** [comment]
Salut, tu peux envoyer app/tmp/error.log ? Et s'il y a le database.log ?
