### ISSUE TITLE
[BUG] Skin system API dont work.

### ISSUE THREAD

**Issue by TOWUK** [MineWeb/MineWebCMS#213]
in docs dont have tutorial how to use skin system mineWeb
(i use openserver / ospanel io localwebserver win)
![image](https://user-images.githubusercontent.com/28830162/82689108-a3f9b300-9c62-11ea-9060-c7ccf7374336.png)
![image](https://user-images.githubusercontent.com/28830162/82689139-b116a200-9c62-11ea-81e5-5f24b85e51b7.png)
and MOTD function not see my spigot server
![image](https://user-images.githubusercontent.com/28830162/82689354-005cd280-9c63-11ea-8ebe-0f67cbf9c388.png)
and banlist show my spigot server...
![image](https://user-images.githubusercontent.com/28830162/82689413-18345680-9c63-11ea-8dd2-c770b967076d.png)

**Comment by KuroSenseii** [comment]
not a bug skin systeme its for website not for server

**Comment by Junior007dj** [comment]
Yes, it's just for the website, not in-game 😉

**Comment by Eywek** [comment]
you need mods that allows you to update minecraft skins, you can't do that on a vanilla server.
