### ISSUE TITLE
[BUG] Https sur le serveur ! 

### ISSUE THREAD

**Issue by Junior007dj** [MineWeb/MineWebCMS#214]
Bonjour je suis déjà venue vers vous auparavant, et je vous en remercie ! 

Je reviens actuellement car même en ayant suivis des consigne et votre documentations je n'y arrive pas. 

Mon problème "Activer la sécurité sur le site" (cadenas)

Site: https://fondatoria.ovh
Hebergeur: OVH
Créer: première fois ya environs 7 mois. 
            Deuxième fois, Hier soir. 
Raison: Pages non sécurisé, https validé mais aucun cadenas certifié.
Certificats: Let's Enscrypt, SSL.

Doit je attendre un peu de temp vue que j'ai recréer mon site ou ya t'il une manip à faire ?

Merci du support, je peut en discuter en details, si vous le souhaiter.

![Screenshot_20200524_163735_com android chrome](https://user-images.githubusercontent.com/60999467/82756871-17bfcb00-9ddd-11ea-9eac-ba308425b51b.jpg)
![Screenshot_20200524_163757_com android chrome](https://user-images.githubusercontent.com/60999467/82756880-1ee6d900-9ddd-11ea-9e05-9d90926e997b.jpg)
![Screenshot_20200524_163807_com android chrome](https://user-images.githubusercontent.com/60999467/82756882-20180600-9ddd-11ea-9901-255e15469aed.jpg)

**Comment by MaximeMichaud** [comment]
Probablement du Mixed-Content. Pour le moment, j'ai juste une page blanche.
Ce n'est pas un problème du côté de MineWeb.

**Comment by Junior007dj** [comment]
C'est a dire ? 
Comment le résoudre ?
Merci du support sinon !

**Comment by MaximeMichaud** [comment]
Si tu veux pas te cassé la tête, tu peux utiliser Cloudflare.

**Comment by Junior007dj** [comment]
Aucune manipulation a faire ? juste je réinstalle mon site puis je fais la manip cloudflare ?

parce que je galère a le sécurisé, sa fait 2 fois qu'on remet la configuration a 0 !

mais merci du support rapide, je m'y attender pas ;)

**Comment by MaximeMichaud** [comment]
Je ne suis pas sûr, de comprendre.
Pour Cloudflare, cela ne concerne pas le CMS, mais plutôt le domaine.
Suffit de changer les nameservers pour ceux de CF et c'est bon.

Pour le support MineWeb, tu as toujours leur support sur le Discord.
Je ne sais pas si leur support est inactif, je n'y suis plus.

**Comment by Junior007dj** [comment]
Il y à le support mais pas pour de grand support de ce type, aide mise a jour et bug de thème.
Le problème sans trop me répéter c'est que des que mon site est installer avec le thème par défaut et que je met quelques plugins avec un thème il reviens en "non sécurisé".

Donc je suis perdu...

**Comment by MaximeMichaud** [comment]
Bah Cloudflare.
C'est le plus vite et moins compliqué, sans te posé trop de questions.
