### ISSUE TITLE
Proposition de changement d'algorithme de chiffrement de mot de passe

### ISSUE THREAD

**Issue by Hypario** [MineWeb/MineWebCMS#218]
Hello !

En lisant le code du CMS, je me suis rendu compte que vous êtiez passé à bcrypt pour chiffrer les mots de passe. Il faudrait passer sur du Argon2ID qui est un bien meilleur algorithme de chiffrement.

Si j'ai le temps, je pourrais regarder le code plus en profondeur et faire un pull request.

**Comment by nivcoo** [comment]
Salut, on a pas changé de méthode de chiffrement seulement ajouté une autre méthode parmi les autres, donc si tu souhaites ajouter Argon2ID a la liste tu peux

**Comment by Hypario** [comment]
C'est ce que je me demandais, vu comment fonctionne CakePHP sur le chiffrement (avec Security), je me posais la question
