### ISSUE TITLE
Proposition d'amélioration : menu latéral "suit" la navigation sur le back-office

### ISSUE THREAD

**Issue by jaz-on** [MineWeb/MineWebCMS#222]
**Proposition**

Laisser l'arborescence du menu du back-office ouvert sur le menu sélectionné lorsque l'on change de page plutôt que de tout refermer.

**To Reproduce | Pour reproduire**

1. Je me connecte tranquillou billou sur mon back-office
![Screenshot_2020-08-02 Accueil Admin](https://user-images.githubusercontent.com/56646501/89124051-47bdd580-d4d4-11ea-957a-e73a385e6609.png)

2. Dans le menu latéral à ma gauche, je navigue pour sélectionner la page que je veux afficher

![Screenshot_2020-08-02 Accueil Admin(1)](https://user-images.githubusercontent.com/56646501/89124071-789e0a80-d4d4-11ea-9903-d0967d3dc8a5.png)

3. Je clique sur un lien (par exemple : Thèmes)

4. J'arrive bien sur la page des thèmes.

![Screenshot_2020-08-02 Liste des thèmes Admin](https://user-images.githubusercontent.com/56646501/89124104-a08d6e00-d4d4-11ea-8261-f58ef4a4d761.png)

**Improvement**

Ce serait surement bien plus clair si le menu restait ouvert et positionné sur l'élément correspond à la page que nous affichons.

**Comment by jaz-on** [comment]
Oupsi. Je ne voulais pas ajouter le label "bug". Je vous laisse le supprimer. Merci :)

**Comment by Eywek** [comment]
C'est le cas mtn @nivcoo non?

**Comment by nivcoo** [comment]
Maintenant quand tu es sur une url qui est présente dans la navbar alors ça laisse le menu / le bouton déployé
