### ISSUE TITLE
Gestion des permissions/utilisateurs.

### ISSUE THREAD

**Issue by AlzheTV** [MineWeb/MineWebCMS#223]
**Describe the bug | Décrivez le bug**

L'on voit des catégories que nous devrions pas voir ou mettre comme permissions.
(Donc bug de permissions). Si on clique dessus, on a une page en désaccord avec le thème actif.

**To Reproduce | Pour reproduire le bug**

1. Créer un compte
2. Lui attribuer certaines permissions.
3. Aller dans le panel administrateur.
4. On voit qu'on peut voir certaines catégories (dont une qui vient du CMS direct, et non d'un plugin : "Serveurs").

5. Si on clique dessus : on obtiens cette erreur (alors qu'on a un thème Justice par MrSheepSheep, par exemple).

**Expected behavior | Ce qui aurait dû se passer**

Nous ne devrions pas voir cette catégorie, ni aucune autre, uniquement la catégorie de la permission "cochée".

**Screenshots**

4. On voit qu'on peut voir certaines catégories (dont une qui vient du CMS direct, et non d'un plugin : "Serveurs").
![bug2permission](https://user-images.githubusercontent.com/68754021/90316332-bc0b6680-df21-11ea-801e-0846f4416750.PNG)

5. Si on clique dessus : on obtiens cette erreur (alors qu'on a un thème Justice par MrSheepSheep, par exemple) (et ça fait ça avec tout les thèmes, mais le bug étant que les permissions refusent juste l'accès, et ne permettent pas de ne pas afficher les catégories, je sais pas si c'est compréhensible).
![bug](https://user-images.githubusercontent.com/68754021/90316359-e8bf7e00-df21-11ea-9011-8f4a5fc3b988.PNG)

Ce que nous devrions voir :
![bug2permissionfix](https://user-images.githubusercontent.com/68754021/90316431-70a58800-df22-11ea-88fa-6d79a749ec3d.PNG)

**MineWeb (please complete the following information):**

- Hébergeur Webstrator, mais bug également présent depuis des années sur l'hébergeur Ni-Host, BoxToPlay, MyAlternos...

**Additional context | Remarques**

Le CMS est loin d'être complet côté administration, gestion des membres...et malheureusement ça reste l'un des meilleurs sur le marché aujourd'hui... :(

**Comment by StanByes** [comment]
Je sais que ton issue date un peu mais j'ai fais les Pull Requests qui règle ces deux bugs ;)

**Comment by AlzheTV** [comment]
Hey

Okay, parfait, au moins d'autres utilisateurs pourront en profiter, ou même
moi 😂.

Merci pour le temps passé a développer/fixer l'erreur.
