### ISSUE TITLE
[Question] reCAPTCHA

### ISSUE THREAD

**Issue by GeekCornerGH** [MineWeb/MineWebCMS#227]
Bonjour, je souhaiterais savoir comment le système reCAPTCHA fonctionne et à quels fichiers il fait appel. Merci d'avance pour votre réponse.

**Comment by Eywek** [comment]
Principalement ici: https://github.com/MineWeb/MineWebCMS/blob/1defcb4657af0983ef04e5afb1ac2bf62067e0af/app/Controller/Component/UtilComponent.php#L274. La documentation devrait se trouver sur le site de google si tu cherches des informations sur comment ca fonctionne réellement.
