### ISSUE TITLE
[BUG] Les e-mail ne son pas envoyer a certain platforme

### ISSUE THREAD

**Issue by xzefir** [MineWeb/MineWebCMS#228]
Bonjour, le problème est tous simple à expliquer mais il y a un problème avec l'envoie des mails (verification, ou mot de passe oublier) qui ne sont pas envoyer à certain adresse e-mail de certaine platforme (ex : live.fr, hotmail.fr).

 - OS: Hébergeur Web (Webstrator)
 - Browser you use to access to MineWeb : Brave
 - Version : 1.7.0
 - Web server : Hebergeur web MineWeb

**Comment by MaximeMichaud** [comment]
Salut,
Outlook/Hotmail est plus capricieux.
Tu as besoin d'un serveur SMTP "vérifié" soit Mailchimp/Mailgun(etc etc)
Autrement, si tu utilises la fonction PHP, il n'y aura pas de mail d'envoyer ou du moins cela sera envoyer en mail indésirable.
Pareillement pour l'envoi de mail via un serveur SMTP interne bien configuré. (Pour Hotmail/outlook uniquement)

Ceci n'est pas un bug.
