### ISSUE TITLE
Traduire les thèmes en anglais

### ISSUE THREAD

**Issue by AQRRastiq** [MineWeb/MineWebCMS#229]
Bonjour,
Pouvez-vous traduire en anglais les thèmes et mettre une option pour choisir la langue s'il vous plaît
Merci par avance

**Comment by Eywek** [comment]
Le CMS est normalement déjà dispo en anglais, si des textes en particulier ne le sont pas pour un thème en particulier, je t'invite à créer une issue sur le thème et non sur le CMS. Merci

**Comment by nivcoo** [comment]
https://github.com/MineWeb/MineWebCMS/pull/244

Tu pourras ajouter des langues comme pour les plugins et gérer ça dans les paramètres généraux du cms. Pour une langue par utilisateur c'est pas possible avec ce système
