### ISSUE TITLE
Problème d'upload

### ISSUE THREAD

**Issue by Goldfire2** [MineWeb/MineWebCMS#231]
Bonjour, 
j'ai un problème avec Mineweb...
Partout où il faut upload des images, ça ne fonctionne pas. Aucune erreur mais rien ne s'upload (slider, logo etc...).
Avez-vous une solution ?

Merci d'avance 👍

**Comment by MaximeMichaud** [comment]
Bonjour,
Le support est sur discord.
Bonne soirée,

**Comment by Goldfire2** [comment]
C'est un bug non ?

**Comment by MaximeMichaud** [comment]
Non.
Problème venant de ton installation/serveur.
Autrement, cela aurait été déjà corrigé.
