### ISSUE TITLE
Ajout d'un choix entre Google Recaptcha & HCaptcha

### ISSUE THREAD

**Issue by FuryCraft** [MineWeb/MineWebCMS#247]
Selon moi, il y a deux grands captcha Google Recaptcha et HCaptcha. De plus en plus de services se tournent vers HCaptcha je pense notamment à Discord. Je pense donc qu'il faudrait avoir une option dans le CMS pour choisir entre les deux

**Comment by nivcoo** [comment]
Bonne idée, je peux facilement le mettre en place mais faudrait faire la modif sur tous les thèmes ^^

**Comment by nivcoo** [comment]
https://github.com/MineWeb/MineWebCMS/pull/248

**Comment by nivcoo** [comment]
Je préviens d'avance, tous les thèmes ne seront pas compatible mais tout sera fait au fur et à mesure, la config actuelle du captcha sera cassé et faudra remettre les clés secrètes
