### ISSUE TITLE
Ajout de fonctionnalités pour le Dark Mode

### ISSUE THREAD

**Issue by FuryCraft** [MineWeb/MineWebCMS#251]
Le Dark Mode est une bonne nouveauté mais on pourrait encore l'améliorer. Par exemple en ajoutant une transition entre le White et le Dark, pourquoi pas un fondu enchainé. De plus le bouton Dark Mode n'est pas animé je trouve ça dommage car il pourrait être animé. Une des fonctionnaalités qui me plairait se serait d'avoir une option pour bloquer le dark mode pour pour toutes les sessions. Toutes les personnes qui se connectent au panel ont le Dark Mode d'activé par défaut.

**Comment by FuryCraft** [comment]
Pour le toggle Dark Mode ce bouton serait plus approprié au design et a une animation: https://codepen.io/garetmckinley/pen/YmxYZr

**Comment by nivcoo** [comment]
Il y a déjà l'animation du bouton

**Comment by FuryCraft** [comment]
Visiblement non, je ne l'ai pas

**Comment by nivcoo** [comment]
Regarde la vidéo https://pics.edensky.fr/2020-12/29/12-20_OWBX.mp4

**Comment by nivcoo** [comment]
Elle est juste un peu plus rapide que ton codepen

**Comment by FuryCraft** [comment]
https://user-images.githubusercontent.com/44116544/103280664-3e785c80-49d1-11eb-9619-388cb934293c.mp4

**Comment by nivcoo** [comment]
Hum je sais pas peut être un script/css qui est en cache, ton navigateur je sais pas

**Comment by FuryCraft** [comment]
Je pense aussi parce que je viens de tester sur mobile et ça fonctionne

**Comment by nivcoo** [comment]
Je close donc ça (pour l'animation de transition c'est également pas possible)

**Comment by nivcoo** [comment]
Car j'ajoute une class donc pas de transition possible
