### ISSUE TITLE
[BUG] Dark Mode

### ISSUE THREAD

**Issue by FuryCraft** [MineWeb/MineWebCMS#252]
Bonjour j'ai vu que le Dark Mode n'était pas compatible sur toutes les pages. Voici donc les pages sur lesquels il n'est pas compatible:
- admin/stats
- admin/statistics
- les input de texte tiny
- admin/news
- admin/serverstatus
Je ne compte pas les plugins car ils ne sont as gérés directement par vous.

**Comment by nivcoo** [comment]
Merci mais tout ce qui est stats (chart) et éditeur HTML ce n'est pas possible de les mettre en dark

**Comment by nivcoo** [comment]
Avec la prochaine maj plusieurs problème du dark mode devrait être réglé
