### ISSUE TITLE
[BUG] DédiPass

### ISSUE THREAD

**Issue by AltisOfLife** [MineWeb/MineWebCMS#273]
**Décrivez le bug**

Bonjour,
J'ai un soucis avec DédiPass, une fois un code DédiPass rentré dans le modules, il redirige vers une page inexistante.. même après avoir supprimée le caches du site..

**Screenshots**

https://uploads.mranthonypvp-g.fr/f.php?h=0Bf2CH3X&p=1

https://uploads.mranthonypvp-g.fr/f.php?h=0YqVT-3L&p=1

**MineWeb (please complete the following information):**

 - OS: FranceServ

 - Navigateur que vous utilisez pour accéder à MineWeb : chrome

 - Version : 1.13.0

 - Web server : [e.g. Apache, nginx] Aucune idée, Debian GNU/Linux 10 (buster), PHP 7.2
 
 - Path to logs : https://paste.md-5.net/fakubawure.shell

**Comment by AltisOfLife** [comment]
??

**Comment by MaximeMichaud** [comment]
Salut, je ne peux pas t'aider, je ne suis pas au courant malheureusement.
Essai de contacté directement le support sur le Discord.
Si le problème n'est pas un cas isolé, alors cela signifie que cela n'est pas un BUG.

Également, cela ne ferait pas de mal d'augmenté ta version PHP vers 7.4. Tu ne risques rien. Plus 7.2 n'est plus maintenu par l'équipe PHP
ref : https://www.php.net/supported-versions.php

**Comment by AltisOfLife** [comment]
Salut,
Merci à vous, je suis passer en 7.4, mon problème est toujours d'actualité..

**Comment by MaximeMichaud** [comment]
Salut, 
Il y a un salon support sur le serveur discord.
