### ISSUE TITLE
Bug Boutique " Erreur : Veuillez remplir tous les champs"

### ISSUE THREAD

**Issue by Fairy-Jeux** [MineWeb/MineWebCMS#276]
Sur mon site web mineweb j'ai un problème que des que je veut ajouter un article sur ma boutique il me met " Erreur : Veuillez remplir tous les champs" alors que tout les champ sont remplis

**Comment by Fairy-Jeux** [comment]
> Sur mon site web mineweb j'ai un problème que des que je veut ajouter un article sur ma boutique il me met " Erreur : Veuillez remplir tous les champs" alors que tout les champ sont remplis

**Comment by Zedbaria** [comment]
tu as réussi depuis ?
