### ISSUE TITLE
[BUG] Erreur lors de la création de la database

### ISSUE THREAD

**Issue by Kuosai** [MineWeb/MineWebCMS#282]
[PDOException] SQLSTATE[42000]: Syntax error or access violation: 1142 SELECT command denied to user 'mineweb'@'localhost' for table 'configurations'
#0 /var/www/html/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/html/lib/Cake/Model/Datasource/Database/Mysql.php(348): DboSource->_execute('SHOW FULL COLUM...')
#2 /var/www/html/lib/Cake/Model/Model.php(1397): Mysql->describe(Object(Configuration))
#3 /var/www/html/lib/Cake/Model/Datasource/DboSource.php(2663): Model->schema()
#4 /var/www/html/lib/Cake/Model/Datasource/DboSource.php(1174): DboSource->fields(Object(Configuration))
#5 /var/www/html/lib/Cake/Model/Model.php(3053): DboSource->read(Object(Configuration), Array)
#6 /var/www/html/lib/Cake/Model/Model.php(3025): Model->_readDataSource('first', Array)
#7 /var/www/html/app/Model/Configuration.php(16): Model->find('first')
#8 /var/www/html/app/Model/Configuration.php(31): Configuration->getData()
#9 /var/www/html/app/Controller/AppController.php(122): Configuration->getKey('name')
#10 /var/www/html/lib/Cake/Error/ExceptionRenderer.php(103): AppController->__initConfiguration()
#11 /var/www/html/lib/Cake/Error/ErrorHandler.php(128): ExceptionRenderer->__construct(Object(PDOException))
#12 [internal function]: ErrorHandler::handleException(Object(PDOException))
#13 {main}
Try to remove files on directory /app/tmp/cache/

Aidez moi s'il vous plaît

**Comment by StanByes** [comment]
Ton utilisateur SQL n'a simplement pas de permission sur ta db, pour ce genre de problème je t'invite à aller sur le discord : https://discord.com/invite/3QYdt8r
