### ISSUE TITLE
[BUG] Impossible d'activer la maintenance

### ISSUE THREAD

**Issue by Shykuzo** [MineWeb/MineWebCMS#303]
**Describe the bug | Décrivez le bug**

Une fois dans le panel Admin, dans la section Maintenance, lorsqu'on crée une nouvelle maintenance dédié à une page ou non et qu'on se rend sur cette page en s'étant déconnecté, une erreur s'affiche marquant "Erreur 500 : Erreur Interne, veuillez réessayer".

**To Reproduce | Pour reproduire le bug**

 - Se connecter à son compte Admin.
 - Se rendre dans le panel Admin.
 - Se rendre dans la section Maintenance.
 - Ajouter une maintenance pour une page ou globalement.
 - Activer cette maintenance.
 - Se déconnecter de son compte Admin.
 - Se rendre sur la page où la maintenance à été activée.

**Expected behavior | Ce qui aurait dû se passer**

Normalement, une page de maintenance aurait dû s'afficher avec la raison définie lors de sa création et de son activation.

**Screenshots**

https://imgur.com/a/97IaUkL

**MineWeb (please complete the following information):**

 - OS: CumulusCloud

 - Browser you use to access to MineWeb : Brave (Chrome)

 - Version : 1.12.1

 - Web server : Apache
 
 - Path to logs (upload the content off /app/tmp/logs/error.log to https://hastebin.com/ and give us the link you get | Mettez en ligne sur https://hastebin.com/ le contenu du fichier /app/tmp/logs/error.log et donnez nous le lien qui en résulte): 
 
 https://www.toptal.com/developers/hastebin/evikafiwud.yaml

**Additional context | Remarques**

J'ai aussi remarqué que sur le plugin de Forum de PHPierre, il était devenu impossible de poster quoi que soit car la même erreur s'affichait, je sais que ce plugin n'a pas été fait par les développeurs de MineWeb mais peut-être que cette erreur vient d'un changement dans le code du CMS.

**Comment by nivcoo** [comment]
Salut, il suffit de faire ces changements en attendant la prochaine MAJ : https://github.com/MineWeb/MineWebCMS/commit/41385da04d3225f7d0383800b5e1d53a6d0cf5c1

**Comment by nivcoo** [comment]
Ensuite pour le forum, Aucune idée le plugin n'est plus maintenu par son créateur alors je ne sais pas :/

**Comment by Shykuzo** [comment]
Merci à vous, je vais voir ça tout de suite !
Je vais essayer de faire quelques modifications dans le Forum afin d'essayer de réglé le problème, je ne connais pas d'autres plugins pouvant faire un aussi bon Forum et je suis incapable d'en créer un.

**Comment by Shykuzo** [comment]
Tout est réglé, merci :)

**Comment by nivcoo** [comment]
Concernant le forum, tout a été corrigé également depuis, je close
