### ISSUE TITLE
500 Error que je n'arrive pas a résoudre

### ISSUE THREAD

**Issue by Bibou1494** [MineWeb/MineWebCMS#332]
**quand je veux procéder a l'installation car j'ai eu un problème et j'ai du réinstaller ça me fait 500 Error**
En fait ça me fait
For know reason of this error, please change
`Configure::write('debug', 0);`
to
`Configure::write('debug', 3);`
in file app/Config/core.php line [34.]
mais j'ai fait ça et ça me fait tout le temps cet erreur.
si besoin j'utilise un abonnement gratuit 000webhost mais j'ai même essayer de supprimée app/tmp/cache mais toujours cet erreur.
pouvais vous m'aider svp.
merci en avance.

**Comment by StanByes** [comment]
Merci de passer sur notre Discord @Bibou1494
