### ISSUE TITLE
Problème avec la jonction du joint de carrelage de la salle de bain

### ISSUE THREAD

**Issue by jimmy-rich** [MineWeb/MineWebCMS#39]
Bonjour,

Voilà, je rencontre actuellement un problème dans ma salle de bain, j'ai essayé à mainte reprise d'effectuer la mise en place de mon joint de carrelage malgré cela le joint n'adhère pas.. 

J'ai essayé de vider mon joint de cache ainsi que le joint de cache de culasse, mais aucune différence.. 

Que faire ?

Merci d'avance.

**Comment by KuroSenseii** [comment]
Commence par vider le bain ensuite vide les armoire. Suite a sa tu pourra vider le cache et virer la culasse dégueulasse

**Comment by ClementGuerin** [comment]
Le mieux c'est de se procurer du mortier à joint en faisant toutefois attention à la proportion d'eau dans la mixture pour ne pas trop diluer, la mixture devra être assez liquide mais pas trop non plus pour que ce soit efficace. Ensuite il faut remplir les bords qui doivent être "jointer" si je puis dire. Tu laisses sécher un peu avant de nettoyer le tout avec une raclette souple. Tu termines le nettoyage à l'éponge et hop le tour est joué.
