### ISSUE TITLE
Chargement infini sur vote

### ISSUE THREAD

**Issue by AzhukOffi** [MineWeb/MineWebCMS#41]
Bonjour,
J'ai un problème avec le système de vote plus précisement sur le site serveurs-minecraft.com 
La validation du vote charge indéfiniment sans avoir de erreur de les log de mineweb

Comment régler ce problème ?

**Comment by Eywek** [comment]
C'est plutôt ici qu'il faudrait ouvrir l'issue https://github.com/MineWeb/Plugin-Vote/issues/new ;)
Mais sinon c'est sûrement que tu as mal configuré le type du site de vote et donc le vote n'est jamais vérifié.
