### ISSUE TITLE
Skin qui ne s'affiche pas

### ISSUE THREAD

**Issue by Apo-Alink** [MineWeb/MineWebCMS#44]
Bonjour, j'ai recemment mis à jour Mineweb sous sa version 1.5.3 mais depuis l'API semble ne plus fonctionner, l'upload de skins marche et on peut accéder aux skins mais la fonction qui permet de récupérer la tête d'un skin (https://monsite.com/API/get_head_skin/pseudo/) ne semble pas fonctionner, ce qui fait qu'aucune tête sur mon site n'apparait.

A noter aussi que la fonction capes est active alors que je l'ai bel et bien désactivée.

J'ai supprimé le cache et ai réinstallé la mise à jour une fois mais sans succès.

**Comment by KuroSenseii** [comment]
desactiver l'option des skin dans autres --> api sa sert a rien de l'activer c'est pour afficher les skin UPLOADER

**Comment by Apo-Alink** [comment]
Justement, c'est un peu ce que je veut ^^, j'ai relié l'api à un mod qui affiche les skins upload par les joueurs.

**Comment by KuroSenseii** [comment]
tu veut dire que les skin upload s'affiche in game via ton mod mais sur le site non ?

**Comment by Eywek** [comment]
Corrigé avec https://github.com/MineWeb/MineWebCMS/releases/tag/v1.5.5
