### ISSUE TITLE
Confirmation de l'email à l'inscription

### ISSUE THREAD

**Issue by KuroSenseii** [MineWeb/MineWebCMS#45]
Je viens de remarquer que cette  fonction ne marche tout simplement pas au même titre que l'option qui permet de bloquer un compte si non confirmer par email.

l'email est pas envoyer

**Comment by Eywek** [comment]
Aucun soucis de mon côté je viens de tester. Si l'email n'est pas envoyé c'est sûrement un problème du côté de la configuration du serveur mail.

**Comment by KuroSenseii** [comment]
bizarre pcq les mail sont bien envoyer pour exemple la newletter
