### ISSUE TITLE
API/launcher/

### ISSUE THREAD

**Issue by xPiston** [MineWeb/MineWebCMS#46]
Il y a un petit souci sur l'API launcher fournis par votre site (monsieur.fr/API/launcher/_Piston/mdpsha256/)
Le souci en question c'est que le MDP 256 fonctionne plus en gros j'peux mettre n'importe quoi en MDP dans la requête il vas me l'a valider

**Comment by Eywek** [comment]
Fixé avec ce commit: https://github.com/MineWeb/MineWebCMS/commit/e546a5206a6e6b4906322702043997db4e98a94f
