### ISSUE TITLE
Problème affichage boutique dédipass

### ISSUE THREAD

**Issue by MrAnthonyPvP** [MineWeb/MineWebCMS#47]
Bonjour,
Mon dédipass marcher très bien jusqu’à maintenant il a décidé de ne plus s'affichez dans la boutique, quand nous voulons créditer nos comptes, il n'est plus affichez alors que je beau l'activé .

Succès : Vous avez bien activé Dédipass comme mode de paiement !

**Comment by Eywek** [comment]
C'est plutôt [ici](https://github.com/MineWeb/Plugin-Shop/issues/new) qu'il faut ouvrir l'issue ;). Veuillez donc l'ouvrir au bon endroit avec des logs et un screen de la table `shop__dedipass_configs`.
