### ISSUE TITLE
Comment j'installe un plugin ?

### ISSUE THREAD

**Issue by EspritYT** [MineWeb/MineWebCMS#49]
Je ne sais pas si il faut faire une manip pour installer un plugin mais quand je le glisse dans le fichiers root de mineweb, ça me donne ça

http://prntscr.com/jr73ue

**Comment by KuroSenseii** [comment]
les plugins sont a installer dans app/plugin et faut suivre la doc du plugin !

De toute facon ta pas a faire sa comme sa tu peut les installer via le panel admin du cms. La visiblement sur otn screen ta mal installer le cms tout court
