### ISSUE TITLE
la V5.5 empêche l'inscription

### ISSUE THREAD

**Issue by Hanarion** [MineWeb/MineWebCMS#54]
Bonjour/bonsoir, je me permet de vous écrire pour vous prévenir que depuis la mise à jour 5.5, l'inscription est devenue impossible, en effet lorsque l'on veux s'inscrire nous obtenons le message : " Erreur : Veuillez remplir tous les champs"
Voila voila,
Aurevoir ;)

**Comment by Eywek** [comment]
Bonjour,

Quel thème et quel site ?

**Comment by Eywek** [comment]
#55

**Comment by Eywek** [comment]
C'est fixé du coup
