### ISSUE TITLE
Bug sur le chemin d’accès du panel admin

### ISSUE THREAD

**Issue by Spartan9802** [MineWeb/MineWebCMS#60]
Bonjour,
J'ai découvert que si nous ne sommes pas connectés en tant qu'admin mais que l'on essaie d'accéder à /admin/plugin/, voici quelques exemples.
https://www.neikacraft.fr/admin/build/
http://buildandcraft.eu/admin/build/
https://hawkcraft.fr/admin/plugin/
https://www.mcroyal.fr/admin/plugin/
https://kfaction.net/admin/plugin/

**Comment by KuroSenseii** [comment]
sa affiche le theme de base quoi, rien bien mechant

**Comment by Eywek** [comment]
En effet, quand on est sur le panel admin, le thème par défaut est appliqué (cf. https://github.com/MineWeb/MineWebCMS/blob/master/app/Controller/AppController.php#L460) et donc les pages d'erreurs 404/403/500... sont affichées avec le thème par défaut.

**Comment by KuroSenseii** [comment]
Fix #103 Issue a clore
