### ISSUE TITLE
Translate to EN

### ISSUE THREAD

**Issue by katsil** [MineWeb/MineWebCMS#63]
is there any way to translate your great (really great) mineweb cms to EN? i can do it, if u`ll create list of phrases to translate.

**Comment by katsil** [comment]
sorry. 

okay, another question: is there any way to create form?

**Comment by KuroSenseii** [comment]
form for what ?

**Comment by katsil** [comment]
submission form. like usual contact form

**Comment by KuroSenseii** [comment]
yes you can create it in page plugin
