### ISSUE TITLE
faction

### ISSUE THREAD

**Issue by demon57730** [MineWeb/MineWebCMS#64]
bonjour j'ai install les plugins mais dans le classement il dit toujours Aucune faction trouvée

**Comment by KuroSenseii** [comment]
ta installer le plugin de faction mineweb ?

**Comment by demon57730** [comment]
Oui

**Comment by demon57730** [comment]
pourquoi il est clôturer le probleme n'est pas résolu

**Comment by Eywek** [comment]
Ça n'a rien à faire sur ce repo (https://github.com/MineWeb/Plugin-FactionRanking). Mais tu n'obtiendras pas beaucoup d'aide ici. Viens sur le Discord plutôt. https://discordapp.com/invite/3QYdt8r

**Comment by demon57730** [comment]
je suis deja sur discord et on ma dit d'ecrire ici car sur le discord le message finira par disparaitre
