### ISSUE TITLE
Looking For Translation Support?

### ISSUE THREAD

**Issue by pthoelken** [MineWeb/MineWebCMS#72]
Hi Valentin, 

I hope you can understand me :) Do you looking for a translation support for your cms? I will help you to translate your minecraft cms into german and english. 

If you a looking for an translator you can contact me via mail at me[at]patrick-thoelken.de - so we can talk about the translation stuff. 

Best regards - Patrick

**Comment by KuroSenseii** [comment]
The CMS is already translate in english. If you want translate to German create a pull request

**Comment by pthoelken** [comment]
Yep. I've seen it. I will translate it to german in few weeks and make pull request :-)
