### ISSUE TITLE
Probleme SSL

### ISSUE THREAD

**Issue by W4RTR1X** [MineWeb/MineWebCMS#84]
Salut ,

J'essaye de passer mon site en HTTPS mais voila j'ai un probleme une feuille css ne veux pas se charger :/
Voici un petit screen :
https://imgur.com/KubtAgQ

J'ai repassé le site en HTTP en attendant et en HTTP aucun soucis mais j'aimerai bien que mon site fonctionne au TOP en HTTPS x)
Une idée ?

Cordialement W4RTR1X.

**Comment by KuroSenseii** [comment]
Bonjours, c'est très simple, le site n'existe pas en https d'ou le fais qu'il soit impossible de récupérer la feuille css en https

Un fix sera fais sur le thème

**Comment by W4RTR1X** [comment]
Re,
Normal je l'ai repassé en HTTP, 2 petites secondes je te le remet en HTTPS que tu puisses voir les erreurs.

**Comment by W4RTR1X** [comment]
Re,
Actuellement le site marche très bien mais comme on m'a expliqué c'est un probleme de css de ce que j'ai compris les feuilles ne sont redirigées qu'en HTTP x)

**Comment by KuroSenseii** [comment]
pour moi ton site ne charge tout simplement pas en https page blanche

**Comment by W4RTR1X** [comment]
Re,
Ha bizarre moi je vois sa : 
http://image.noelshack.com/fichiers/2018/43/6/1540639398-capture.png

**Comment by W4RTR1X** [comment]
Re,
Je viens de tester sur mon téléphone et je vois bien une page blanche ...
Aurait-tu une idée d’où sa peux venir ?

**Comment by PHPierrre** [comment]
Aucun problème de mon coté aussi : 
![image](https://user-images.githubusercontent.com/8572485/47679030-81590280-dbc3-11e8-84d6-f92c12f1a105.png)

**Comment by plagoutte** [comment]
Pas de soucis de mon côté non plus, testé avec Firefox pour Windows 10 et Safari pour iOS 12.
