### ISSUE TITLE
Adresses relatives dans les menus déroulants

### ISSUE THREAD

**Issue by plagoutte** [MineWeb/MineWebCMS#93]
Exemple : 

Menu déroulant avec deux liens :
- Page 1 : p/page1
- Page 2 : p/page2

Si j'ouvre page1, pas de soucis. Si, depuis la page 1, je clique sur page2, le navigateur ira sur p/p/page2.

**Comment by nivcoo** [comment]
C'est normal c'est pas comme ca qu'on ajoute une page il y a une option pour ca

**Comment by plagoutte** [comment]
Pas dans les menus multiples malheureusement

**Comment by nivcoo** [comment]
Sinon suffit de mettre http://site.fr/p/ta page.php

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>

________________________________
De : Pierre LAGOUTTE <notifications@github.com>
Envoyé : samedi, novembre 10, 2018 6:53 PM
À : MineWeb/MineWebCMS
Cc : nivcoo; Comment
Objet : Re: [MineWeb/MineWebCMS] Adresses relatives dans les menus déroulants (#93)


Pas dans les menus multiples malheureusement

**Comment by Eywek** [comment]
Tu es sur quel thème?

**Comment by nivcoo** [comment]
Le theme ne change rien c'est juste que dans les sous menus il n'est pas possible de choisir le plugin donc c'est pas les route qui sont pris mais juste /shop ou autre donc ca rajoute le /shop apres la page ou on est, le seul moyen c'est de mettre l'url complet :)
