### ISSUE TITLE
Problème de skins

### ISSUE THREAD

**Issue by Chtioquinquin** [MineWeb/MineWebCMS#94]
Bonsoir, j'ai un problème avec les skins du site, aucun skin ne s'affiche, l'API n'est pas activé.
Voici ce que ça affiche lorsque l'on tente de récupérer un skin: https://lostisland.craftaserv.fr/API/get_head_skin/rominca/64

Merci

**Comment by KuroSenseii** [comment]
toi tes chez craftaserv non ?

**Comment by Chtioquinquin** [comment]
Oui, c'est moi MiStErFiGhT12 sur le discord, c'est juste que j'avais déjà un compte sur github

**Comment by jimmyr57000** [comment]
Problème présent sur la plupart des hébergeur, le soucis à déjà était résolu par PHPierre.

**Comment by Chtioquinquin** [comment]
Pourrais-je avoir des informations là-dessus  s'il vous plaît ?

**Comment by jimmyr57000** [comment]
Hello, 

https://github.com/MineWeb/MineWebCMS/pull/95/commits/aa28936ee251c3399aca2079e305a91c6b1619d9

**Comment by Chtioquinquin** [comment]
Bonjour, j'ai remplacé le code, mais lorsque je tente de récupérer un skin déjà je n'ai plus les lignes de codes j'ai un skin mais le problème c'est que c'est que des steve les skins n'y sont pas

https://www.lostisland.craftaserv.fr/API/get_head_skin/MiStErFiGhT12/25

Page staff avec les têtes: https://www.lostisland.craftaserv.fr/staff

**Comment by KuroSenseii** [comment]
tes sur de ne pas avoir activer l'option api skin ?

**Comment by KuroSenseii** [comment]
a tu suppriemr la ligne 

$this->response->type('image/png'); 

quand tu ma mis la nouvelle ?

**Comment by Chtioquinquin** [comment]
Nan, elles y sont, j'ai essayé de les enlever et le résultat et pareil.

**Comment by KuroSenseii** [comment]
vide le cache et actualise si toujours rien, met le error.logs sur hastebin et envoi le lien

**Comment by Chtioquinquin** [comment]
Le problème c'est que rien n’apparaît dans les logs.
