### ISSUE TITLE
Possible BUG au niveau de l'inscription

### ISSUE THREAD

**Issue by lucas-luchack** [MineWeb/MineWebCMS#98]
Sur mon site ( https://islandgame.fr/minecraft/ ) lors de l'inscription si l'option des CGU est activé ( avec n'importe quel thème ) l'erreur "Veuillez remplir tous les champs" apparaît si on désactive l'option cela marche !
Ce "_bug_" n'était pas présent avant la **1.6.0**

Je ne sais pas si d'autre personne on se problème mais si c'est un bug réel il faudrait qu'il soit corriger rapidement !
_Si vous voulais tester merci de mon contact sur discord (Je suis contributeur) pour que j'active l'option !_

**Comment by Eywek** [comment]
Les thèmes n'affiche pas la case pour ?

**Comment by lucas-luchack** [comment]
Si "Guide" l'affiche

**Comment by KuroSenseii** [comment]
c'est pas un bug au niveau du cms mais du theme, le theme guide n'utilise pas les meme variable que ceux du cms mais plutot ceux de la config du theme.

issue a close

**Comment by nivcoo** [comment]
Il faut donc changer comme a dit kuro la variable mais aussi pourquoi pas le modifier directement sur le thème donc faudrait regarder le code de base avec le <?php if ...... incluant la condition pour le changer sur le thème et enlever donc l'ancien système de la config
