### ISSUE TITLE
Add Php 7.3 support

### ISSUE THREAD

**Issue by x9nico** [MineWeb/MineWebCMS#99]
Bonjour, possible de rajouter le support de la version PHP 7.3 sur Mineweb svp ? :)

**Comment by jimmyr57000** [comment]
Bonsoir,
Il n'est déjà pas compatible avec la 7.2... il faudrait déjà l'adapté sur cette version ;)
En tous cas cela risque d'être compliqué.
Cdt

**Comment by nivcoo** [comment]
https://github.com/MineWeb/MineWebCMS/pull/90

**Comment by Eywek** [comment]
Quand development sera release
